### PR TITLE
feat: added flipper

### PR DESCRIPTION
**Pull request by boredmage**
- Added flipper animation as expected
- Fix some bug fixes regards the standard way of doing some things in ReactJS

### CODE REVIEW

**Comment by VulcanWM** [comment]
Hey dude this is amazing!
The only problem is, with this solution, test mode function isn't working anymore.
Also is there a way you can explain all the changes you have made?

**Comment by boredmage** [comment]
Hi, Test mode function is working correctly. As shown in the preview video
attached to this email.

I added a component that flips and passes it into every child's components
with the state managed in the parent component. So when the td element is
clicked, it changes the state of the clicked element in the parent
component which triggers the flip component for that td to be flipped.

Also for the test too, I added a component for the test which takes the
result as a prop and passed the result in each td.

So in the state, I check if the test mode is active and display the test
component, if not, it should display the flipper component which is named
Hide.

**Comment by boredmage** [comment]
> Hey dude this is amazing! The only problem is, with this solution, test mode function isn't working anymore. Also is there a way you can explain all the changes you have made?

All fixed now.

Didn't understand the logics at first and you didn't mention that, so I don't know about it until you mentioned, but it's now all fixed

**Comment by VulcanWM** [comment]
ayyy, the css is amazing!
thanks for your help!

**Pull request merged**
